---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.0.101:
    agent:
      hosts:
        192.168.0.102:
        192.168.0.103:

  # Required Vars
  vars:
    sops: "{{ lookup('community.sops.sops', '{{ inventory_dir }}/secrets.yaml') | ansible.builtin.from_yaml }}"
    
    ansible_port: 22
    ansible_user: "{{ sops.ansible_user }}"
    k3s_version: v1.30.2+k3s1
    token: "{{ sops.token }}"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: "--disable traefik"
    extra_agent_args: ""

    kube_config: "{{ lookup('ansible.builtin.env', 'KUBECONFIG') }}"
    kube_context: homelab.dev